### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by bigmb** [KeepsakeAutomation/Functional-modules-for-Laser-Cutting-Nesting-#1]
1) Make different body parts of the code.
2) Add comments in the code

**Comment by ncook11** [comment]
Hey, I'm looking through the code on github and I'm not seeing "Final_code_with_imported_functions.py", or "Nested_Shape_Visualisation.FCMacro". Were these files removed from the repository? It seems as though the code now has the exact same problem that started this thread (No comments, and no advice on how to use the code). The Flow chart is there, but it doesn't provide much in the way of advising the user what functions to use and in what order since they seem to be built on top of each other. Help would be really appreciated, thanks!
